export const IS_TABLES = [
  {
    id: 'is-table-plain-concrete',
    label: 'IS Table: Plain & Reinforced Concrete',
    content: {
      title: 'Minimum Cement Content, Maximum Water-Cement Ratio, and Minimum Grade of Concrete for Different Exposures',
      headers: [
        'Exposure',
        'Plain Concrete: Minimum Cement Content (kg/m³)',
        'Plain Concrete: Maximum Free Water-Cement Ratio',
        'Plain Concrete: Minimum Grade of Concrete',
        'Reinforced Concrete: Minimum Cement Content (kg/m³)',
        'Reinforced Concrete: Maximum Free Water-Cement Ratio',
        'Reinforced Concrete: Minimum Grade of Concrete',
      ],
      rows: [
        ['Mild',      '220', '0.60', 'M15', '300', '0.55', 'M20'],
        ['Moderate',  '240', '0.60', 'M15', '300', '0.50', 'M25'],
        ['Severe',    '250', '0.50', 'M20', '320', '0.45', 'M30'],
        ['Very Severe','260','0.45', 'M20', '340', '0.45', 'M35'],
        ['Extreme',   '280', '0.40', 'M25', '360', '0.40', 'M40'],
      ],
    },
  },
  {
    id: 'is-table-fine-aggregate',
    label: 'IS Table: Fine Aggregate',
    content: {
      title: 'Table 9: Fine Aggregates (Clause 6.3)',
      headers: [
        'IS Sieve Designation',
        'Percentage Passing Grading Zone I',
        'Percentage Passing Grading Zone II',
        'Percentage Passing Grading Zone III',
        'Percentage Passing Grading Zone IV',
      ],
      rows: [
        ['10 mm',   '100',   '100',   '100',   '100'],
        ['4.75 mm', '90-100','90-100','90-100','95-100'],
        ['2.36 mm', '60-95', '75-100','85-100','95-100'],
        ['1.18 mm', '30-70', '55-90', '75-100','90-100'],
        ['600 μm',  '15-34', '35-59', '60-79', '80-100'],
        ['300 μm',  '5-20',  '8-30',  '12-40', '15-50'],
        ['150 μm',  '0-10',  '0-10',  '0-10',  '0-15'],
      ],
    },
  },
  {
    id: 'is-table-coarse-aggregate',
    label: 'IS Table: Coarse Aggregate',
    content: {
      title: 'Table 7: Coarse Aggregates (Clauses 5.1 and 6.2)',
      headers: [
        'IS Sieve Designation',
        'Percentage Passing for Single-Sized Aggregate of Nominal Size (mm): 63',
        '40',
        '20',
        '16',
        '12.5',
        '10',
        'Percentage Passing for Graded Aggregate of Nominal Size (mm): 40',
        '20',
        '16',
        '12.5',
      ],
      rows: [
        ['80 mm',    '100', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
        ['63 mm',    '85-100', '100', '-', '-', '-', '-', '-', '-', '-', '-'],
        ['40 mm',    '0-30', '85-100', '100', '-', '-', '100', '-', '-', '-', '-'],
        ['20 mm',    '0-5', '0-20', '85-100', '100', '-', '95-100', '100', '-', '-', '-'],
        ['16 mm',    '-', '-', '0-20', '85-100', '100', '-', '90-100', '100', '-', '-'],
        ['12.5 mm',  '-', '-', '0-5', '0-20', '85-100', '100', '-', '90-100', '100', '100'],
        ['10 mm',    '-', '-', '-', '-', '0-20', '85-100', '-', '-', '85-100', '100'],
        ['4.75 mm',  '-', '-', '-', '-', '0-5', '0-10', '-', '-', '0-20', '0-20'],
        ['2.36 mm',  '-', '-', '-', '-', '-', '-', '-', '-', '0-5', '0-5'],
      ],
    },
  },
  {
    id: 'is-table-assumed-sd',
    label: 'IS Table: Assumed Standard Deviations',
    content: {
      title: 'Table 2: Assumed Standard Deviation (Clause 4.2.1.3)',
      headers: [
        'Grade of Concrete',
        'Assumed Standard Deviation (N/mm²)',
      ],
      rows: [
        ['M10',  '3.5'],
        ['M15',  '3.5'],
        ['M20',  '4.0'],
        ['M25',  '4.0'],
        ['M30',  '5.0'],
        ['M35',  '5.0'],
        ['M40',  '5.0'],
        ['M45',  '5.0'],
        ['M50',  '5.0'],
      ],
    },
  },
  {
    id: 'is-table-sieve-size',
    label: 'IS Table: Sieve Size Analysis of Coarse Aggregate',
    content: {
      title: 'Sieve Analysis of Coarse Aggregate Fractions and Percentage of Different Fractions',
      headers: [
        'IS Sieve Sizes (mm)',
        'Analysis of Coarse Aggregate Fraction I (20-10 mm) (%)',
        'Analysis of Coarse Aggregate Fraction II (10-4.75 mm) (%)',
        'Percentage of Fraction I (60%)',
        'Percentage of Fraction II (40%)',
        'Total Conforming (%)',
        'Remarks',
      ],
      rows: [
        ['20',    '100',   '100',   '60',   '40',   '100',   '-'],
        ['10',    '0',     '71.20', '0',    '28.5', '28.5',  'Conforming to Table 7 of IS 383'],
        ['4.75',  '-',     '9.40',  '-',    '3.7',  '3.7',   '-'],
        ['2.36',  '-',     '0',     '-',    '0',    '-',     '-'],
      ],
    },
  },
  {
    id: 'is-table-value-x',
    label: 'IS Table: Value of X',
    content: {
      title: 'Value of X for Different Grades',
      headers: [
        'Grade',
        'X',
      ],
      rows: [
        ['10', '5'],
        ['15', '5'],
        ['20', '5.5'],
        ['25', '5.5'],
        ['30', '6.5'],
        ['35', '6.5'],
        ['40', '6.5'],
        ['45', '6.5'],
        ['50', '6.5'],
        ['55', '6.5'],
        ['60', '6.5'],
        ['70', '8'],
        ['75', '8'],
        ['80', '8'],
      ],
    },
  },
  {
    id: 'is-table-min-cement-content',
    label: 'IS Table: Minimum Cement Content, Maximum Water-Cement Ratio',
    content: {
      title: 'Minimum Cement Content, Maximum Water-Cement Ratio for Reinforced Concrete',
      headers: [
        'Minimum Cement (kg/m³)',
        'Maximum Water-Cement Ratio',
        'Minimum Grade of Concrete',
      ],
      rows: [
        ['300', '0.55', '20'],
        ['300', '0.50', '25'],
        ['320', '0.45', '30'],
        ['340', '0.45', '35'],
        ['360', '0.40', '40'],
        ['300', '0.55', '15'],
      ],
    },
  },
  {
    id: 'is-table-water-content',
    label: 'IS Table: Water Content per Cubic Meter',
    content: {
      title: 'Water Content per Cubic Meter of Nominal Size',
      headers: [
        'Nominal Size (mm)',
        'Water Content (kg)',
      ],
      rows: [
        ['10', '208'],
        ['20', '186'],
        ['40', '165'],
      ],
    },
  },
  {
    id: 'is-table-coarse-aggregate-volume',
    label: 'IS Table: Volume of Coarse Aggregate per Unit Volume of Total Aggregate',
    content: {
      title: 'Volume of Coarse Aggregate per Unit Volume of Total Aggregate',
      headers: [
        'Size (mm)',
        'Zone 1',
        'Zone 2',
        'Zone 3',
        'Zone 4',
      ],
      rows: [
        ['10', '0.48', '0.50', '0.52', '0.54'],
        ['20', '0.60', '0.62', '0.64', '0.66'],
        ['40', '0.69', '0.71', '0.72', '0.73'],
      ],
    },
  },
  {
    id: 'is-table-approximate-air-content',
    label: 'IS Table: Approximate Air Content',
    content: {
      title: 'Approximate Air Content',
      headers: [
        'Size (mm)',
        'Entrapped Air (%)',
      ],
      rows: [
        ['10', '1.5'],
        ['20', '1.0'],
        ['40', '0.8'],
      ],
    },
  },
];
